from typing import List

chaos_effects: List[str] = [
    "Target creature <ansigreen>gets +3/+3</ansigreen> until end of turn.",
    "Deal <ansired>2 damage</ansired> to target creature or player.",
    "Put a 1/1 Servo artifact creature token under your control.",
    "<ansiyellow>Gain 3 life</ansiyellow>.",
    "Each opponent may <ansiblue>draw 1 card</ansiblue>.",
    "<ansired>Destroy</ansired> target artifact or enchantment.",
    "<ansiblue>Exchange control</ansiblue> of target creature you control and target creature you don't control.",
    "Each player <style fg='#aa00ff'>discards 1 card.</style>",
    "Each opponent <ansiyellow>gains 4 life</ansiyellow>, you <ansiblue>draw 2 cards</ansiblue>.",
    "You may <u>play</u> <ansigreen>up to 3 aditional lands</ansigreen> this turn.",
    "Each player, starting with you, <u>plays</u> the top instant/sorcery card in their <b>graveyard</b>, <u>without paying</u> its cost.",
    "Each player <style fg='#aa00ff'>sacrifices a creature.</style>",
    "<ansired>Destroy</ansired> any creature.",
    "You <style fg='#aa00ff'>sacrifice 1 permanent</style>.",
    "<ansigreen>Put a +1/+1 counter</ansigreen> on target creature.",
    "Each player <u>reveals</u> a card at <u>random</u> from their <b>hand</b> and takes <ansired>damage</ansired> equal to its CMC.",
    "You are the <ansiblue>monarch</ansiblue>.",
    "Each player <ansiblue>draws 1 card.</ansiblue>",
    "<style fg='#aa00ff'>Sacrifice</style> 1 creature, <style fg='#aa00ff'>sacrifice</style> 1 land, <style fg='#aa00ff'>discard</style> 1 card and <style fg='#aa00ff'>lose</style> 1 life.",
    "<ansiblue>Tap</ansiblue> up to 3 target creatures.",
    "You may <u>return</u> a creature card from your <b>graveyard</b> to your <b>hand</b>.",
    "You may <u>search</u> your <b>library</b> for a basic land card and <u>put it into play tapped</u>.",
    "Each player <style fg='#aa00ff'>loses 1 life</style>.",
    "All creatures <ansired>take 2 damage</ansired>.",
    "You may <u>play</u> a creature <u>without paying</u> its cost. If you do, each opponent creates a 2/2 Knight creature token with first strike.",
    "Target player <ansigreen>gets 4 poison counters</ansigreen>.",
    "You <ansiyellow>gain 2 life</ansiyellow> for each card in your <b>hand</b>.",
    "You may <u>return</u> an instant/sorcery from your <b>graveyard</b> to your <b>hand</b>.",
    "You may <u>copy</u> the next instant/sorcery <u>played</u> by an opponent.",
    "<u>Shuffle</u> target permanent into its owner's <b>library</b>. That player <ansiblue>draws 2 cards</ansiblue>.",
    "Each player may <ansiblue>scry 1</ansiblue>.",
    "Target creature <ansiyellow>gains protection</ansiyellow> from the color of your choice until end of turn.",
    "<u>Remove</u> target creature from the game.",
    "You may <u>search</u> your <b>library</b> for any card and <u>put it 3rd from the top</u> of your <b>library</b>.",
    "<ansired>Destroy all</ansired> creatures.",
    "You may <u>remove up to 4 cards</u> from target player's <b>graveyard</b>.",
    "<u>Shuffle</u> your <b>graveyard</b> into your <b>library</b>.",
    "You <ansiblue>get an extra turn</ansiblue> after this one.",
    "<ansiblue>Scry 2</ansiblue>, then <ansiblue>draw a card</ansiblue>.",
    "<u>Shuffle</u> a card from your <b>hand</b> into your <b>library</b> and <ansiblue>draw a card</ansiblue>.",
    "You may <ansiyellow>gain 7 life</ansiyellow>. If you do, each opponent <ansiblue>draws 1 card</ansiblue>.",
    "You <ansiblue>gain control</ansiblue> of target creature until end of the turn, it <ansired>gets haste</ansired>.",
    "Target opponent <ansiblue>gains control</ansiblue> of one of your creatures <ansiblue>permanently</ansiblue>.",
    "You <ansired>must attack left</ansired> this turn.",
    "Each player <ansiblue>draws 2 cards</ansiblue>.",
]
